# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: check-yaml
      - id: check-added-large-files
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
      - id: file-contents-sorter
        files: .gitignore

  # Format files using black
  - repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
      - id: black

  # PEP8 compliant import ordering
  - repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
      - id: isort
        additional_dependencies: ["toml"]
